version: '3.6'

networks:
  appdtr:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: ./.config/php/Dockerfile
    working_dir: /usr/srv
    container_name: php-${APP_NAME}
    volumes:
      - ./backend:/usr/srv
    ports:
      - ${PHP_PORT}:9000
    networks:
      - appdtr

  node:
    image: node:12.16.1
    container_name: node-${APP_NAME}
    tty: true
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    # command tail -F is added so container won't exit
    # command: sh -c "yarn install && tail -F /anything/here"
    networks:
      - appdtr

  nginx-back:
    image: nginx:1.17
    container_name: nginx-back-${APP_NAME}
    depends_on: 
      - php
    # restart: always
    ports:
      - 8000:80
      # - 8001:443 #For port when using SSL
    volumes:
      - ./backend:/usr/srv
      - ./.config/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appdtr

  nginx-front:
    image: nginx:1.17
    container_name: nginx-front-${APP_NAME}
    # restart: always
    ports: 
      - 10080:80
      - 10081:443
    volumes: 
      - ./frontend:/var/www/
      - .config/nginx/frontend.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    container_name: mysql-${APP_NAME}
    ports:
      - ${DB_PORT}:3306
    tty: true
    depends_on:
      - nginx-back
    volumes:
      - ./.config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - appdtr

  phpadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: phpadmin-${APP_NAME}
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - appdtr