version: '3.6'

networks:
  appdtr:
    driver: bridge

services:
  php:
    build:
      context: .
      dockerfile: ./.config/php/Dockerfile
    working_dir: /usr/srv
    container_name: php-${APP_NAME}
    volumes:
      - ./backend:/usr/srv
    ports:
      - ${PHP_PORT}:9000
    environment: 
      DB_HOST: ${DB_HOST}
    # command: sh -c "composer install -n --no-progress --prefer-dist && php-fpm"
    networks:
      - appdtr

  node:
    image: node:12.16.1
    container_name: node-${APP_NAME}
    tty: true
    working_dir: /var/www
    volumes:
      - ./frontend:/var/www
    command: sh -c "yarn install && node"
    networks:
      - appdtr

  nginx-back:
    image: nginx:1.17
    container_name: nginx-back-${APP_NAME}
    depends_on: 
      - php
    # restart: always
    ports:
      - ${BACKEND_PORT}:80
      - ${BACKEND_PORT_WITH_SSL}:443 #For port when using SSL
    volumes:
      - ./backend:/usr/srv
      - ./.config/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appdtr

  nginx-front:
    image: nginx:1.17
    container_name: nginx-front-${APP_NAME}
    depends_on: 
      - node
    # restart: always
    ports: 
      - ${FRONTEND_PORT}:80
      - ${FRONTEND_PORT_WITH_SSL}:443
    volumes: 
      - ./frontend:/var/www/
      - .config/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
      - .config/nginx/front-gzip.conf:/etc/nginx/conf.d/compression.conf

  mysql:
    image: mysql:8.0
    container_name: mysql-${APP_NAME}
    ports:
      - ${DB_PORT}:3306
    tty: true
    depends_on:
      - php
      - nginx-back
    volumes:
      - ./.config/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - appdtr

  composer:
    image: composer:1.10
    container_name: composer-${APP_NAME}
    depends_on: 
      - php
    tty: true
    working_dir: /usr/srv
    volumes:
      - ./backend:/usr/srv
    # command tail -F is added so container won't exit
    command: sh -c "composer install -n --no-progress && tail -F /anything/unknown/here"
    networks:
      - appdtr

  phpadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: phpadmin-${APP_NAME}
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - appdtr