name: Docker

on:
  push:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:      
    - uses: actions/checkout@v2

    - name: Check docker version
      run: docker --version

    - name: Build php image
      run: docker build -f .config/php/Dockerfile .
      
   